name: react-vue deploy container

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'react-vue/container/**'

defaults:
  run:
    working-directory: 'react-vue/container'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build artifacts
        run: npm run build

#      - name: Setup AWS CLI
#        uses: chrislennon/action-aws-cli@v1.1

      - name: Sync dist directory with s3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
